"""Thêm cấu hình sinh ảnh bìa tiểu thuyết

Revision ID: 8e3ac0236b27
Revises: d4d253e3f4c6
Create Date: 2026-03-16 10:56:31.489936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3ac0236b27'
down_revision: Union[str, None] = 'd4d253e3f4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('cover_image_url', sa.String(length=1000), nullable=True, comment='URL truy cập ảnh bìa'))
    op.add_column('projects', sa.Column('cover_prompt', sa.Text(), nullable=True, comment='Prompt đã dùng để sinh ảnh bìa lần gần nhất'))
    op.add_column('projects', sa.Column('cover_status', sa.String(length=20), nullable=False, server_default='none', comment='Trạng thái ảnh bìa: none/generating/ready/failed'))
    op.add_column('projects', sa.Column('cover_error', sa.Text(), nullable=True, comment='Lý do thất bại sinh ảnh bìa lần gần nhất'))
    op.add_column('projects', sa.Column('cover_updated_at', sa.DateTime(), nullable=True, comment='Thời gian sinh ảnh bìa thành công lần gần nhất'))
    op.add_column('settings', sa.Column('cover_api_provider', sa.String(length=50), nullable=True, comment='Nhà cung cấp API ảnh bìa'))
    op.add_column('settings', sa.Column('cover_api_key', sa.String(length=500), nullable=True, comment='API key ảnh bìa'))
    op.add_column('settings', sa.Column('cover_api_base_url', sa.String(length=500), nullable=True, comment='Địa chỉ API tùy chỉnh ảnh bìa'))
    op.add_column('settings', sa.Column('cover_image_model', sa.String(length=100), nullable=True, comment='Tên model ảnh bìa'))
    op.add_column('settings', sa.Column('cover_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false'), comment='Có bật sinh ảnh bìa không'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'cover_enabled')
    op.drop_column('settings', 'cover_image_model')
    op.drop_column('settings', 'cover_api_base_url')
    op.drop_column('settings', 'cover_api_key')
    op.drop_column('settings', 'cover_api_provider')
    op.drop_column('projects', 'cover_updated_at')
    op.drop_column('projects', 'cover_error')
    op.drop_column('projects', 'cover_status')
    op.drop_column('projects', 'cover_prompt')
    op.drop_column('projects', 'cover_image_url')
    # ### end Alembic commands ###