"""Thêm trường theo dõi trạng thái tâm lý nhân vật

Revision ID: d4d253e3f4c6
Revises: 421237957b27
Create Date: 2026-02-12 12:44:20.266679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d253e3f4c6'
down_revision: Union[str, None] = '421237957b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('status', sa.String(length=20), nullable=True, comment='Trạng thái: active/deceased/missing/retired/destroyed'))
    op.add_column('characters', sa.Column('status_changed_chapter', sa.Integer(), nullable=True, comment='Số chương thay đổi trạng thái'))
    op.add_column('characters', sa.Column('current_state', sa.Text(), nullable=True, comment='Trạng thái tâm lý hiện tại của nhân vật (phân tích tự cập nhật)'))
    op.add_column('characters', sa.Column('state_updated_chapter', sa.Integer(), nullable=True, comment='Số chương cập nhật trạng thái tâm lý gần nhất'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'state_updated_chapter')
    op.drop_column('characters', 'current_state')
    op.drop_column('characters', 'status_changed_chapter')
    op.drop_column('characters', 'status')
    # ### end Alembic commands ###