"""Thêm bảng quản lý phục bút

Revision ID: 6a73f37e9adb
Revises: a7e4408e1d5b
Create Date: 2026-01-19 17:29:23.350443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a73f37e9adb'
down_revision: Union[str, None] = 'a7e4408e1d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreshadows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Tiêu đề phục bút'),
    sa.Column('content', sa.Text(), nullable=False, comment='Nội dung/mô tả chi tiết phục bút'),
    sa.Column('hint_text', sa.Text(), nullable=True, comment='Văn bản ám chỉ khi gieo phục bút(trích nguyên văn hoặc tóm tắt)'),
    sa.Column('resolution_text', sa.Text(), nullable=True, comment='Văn bản hé lộ khi thu hồi phục bút(trích nguyên văn hoặc tóm tắt)'),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='Loại nguồn: analysis=trích xuất phân tích, manual=thêm thủ công'),
    sa.Column('source_memory_id', sa.String(length=100), nullable=True, comment='ID ký ức nguồnID(nếu đồng bộ từ kết quả phân tích)'),
    sa.Column('source_analysis_id', sa.String(length=36), nullable=True, comment='ID task phân tích nguồn'),
    sa.Column('plant_chapter_id', sa.String(length=36), nullable=True, comment='ID chương gieo vàoID'),
    sa.Column('plant_chapter_number', sa.Integer(), nullable=True, comment='Số chương gieo vào(lưu dư thừa để tiện truy vấn)'),
    sa.Column('target_resolve_chapter_id', sa.String(length=36), nullable=True, comment='ID chương dự kiến thu hồiID'),
    sa.Column('target_resolve_chapter_number', sa.Integer(), nullable=True, comment='Số chương dự kiến thu hồi'),
    sa.Column('actual_resolve_chapter_id', sa.String(length=36), nullable=True, comment='ID chương thu hồi thực tếID'),
    sa.Column('actual_resolve_chapter_number', sa.Integer(), nullable=True, comment='Số chương thu hồi thực tế'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='\n    Trạng thái phục bút:\n    - pending: chờ gieo(đã lên kế hoạch nhưng chưa viết vào chương)\n    - planted: đã gieo(đã gieo trong chương)\n    - resolved: đã thu hồi(đã thu hồi trong chương)\n    - partially_resolved: thu hồi một phần(Phục bút dài hơi có thể thu hồi nhiều lần)\n    - abandoned: đã loại bỏ(đã quyết định không dùng phục bút này nữa)\n    '),
    sa.Column('is_long_term', sa.Boolean(), nullable=True, comment='Có phải phục bút dài hơi không(Phục bút quan trọng xuyên nhiều chương)'),
    sa.Column('importance', sa.Float(), nullable=True, comment='Điểm quan trọng 0.0-1.0'),
    sa.Column('strength', sa.Integer(), nullable=True, comment='Cường độ phục bút 1-10(mức độ ảnh hưởng tới độc giả mạnh cỡ nào)'),
    sa.Column('subtlety', sa.Integer(), nullable=True, comment='Mức độ ẩn 1-10 (càng cao càng kín đáo)'),
    sa.Column('urgency', sa.Integer(), nullable=True, comment='Mức khẩn cấp: 0=không khẩn cấp, 1=cần chú ý, 2=cần thu hồi gấp'),
    sa.Column('related_characters', sa.JSON(), nullable=True, comment="Danh sách tên nhân vật liên quan: ['角色1', '角色2']"),
    sa.Column('related_foreshadow_ids', sa.JSON(), nullable=True, comment='Danh sách ID phục bút liên quan khác (chuỗi phục bút)'),
    sa.Column('tags', sa.JSON(), nullable=True, comment="Danh sách tag: ['身世', '悬念', '反转']"),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Phân loại: identity(thân thế), mystery(hồi hộp), item(vật phẩm), relationship(quan hệ), event(sự kiện)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Ghi chú sáng tác(chỉ tác giả thấy)'),
    sa.Column('resolution_notes', sa.Text(), nullable=True, comment='Giải thích cách thu hồi'),
    sa.Column('auto_remind', sa.Boolean(), nullable=True, comment='Có tự động nhắc khi sinh chương không'),
    sa.Column('remind_before_chapters', sa.Integer(), nullable=True, comment='Bắt đầu nhắc thu hồi trước mấy chương'),
    sa.Column('include_in_context', sa.Boolean(), nullable=True, comment='Có đưa vào ngữ cảnh sinh không'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Thời gian cập nhật'),
    sa.Column('planted_at', sa.DateTime(), nullable=True, comment='Thời gian gieo'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='Thời gian thu hồi'),
    sa.ForeignKeyConstraint(['actual_resolve_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_resolve_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadows_project_id'), 'foreshadows', ['project_id'], unique=False)
    op.create_index(op.f('ix_foreshadows_status'), 'foreshadows', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foreshadows_status'), table_name='foreshadows')
    op.drop_index(op.f('ix_foreshadows_project_id'), table_name='foreshadows')
    op.drop_table('foreshadows')
    # ### end Alembic commands ###