"""Thêm cấu trúc bảng liên quan xưởng prompt

Revision ID: 421237957b27
Revises: 6a73f37e9adb
Create Date: 2026-01-27 14:04:47.054011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421237957b27'
down_revision: Union[str, None] = '6a73f37e9adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_submissions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('submitter_id', sa.String(length=255), nullable=False, comment='Định danh người gửi (ID instance:ID người dùng)'),
    sa.Column('submitter_name', sa.String(length=100), nullable=True, comment='Tên hiển thị người gửi'),
    sa.Column('source_instance', sa.String(length=255), nullable=False, comment='Định danh instance nguồn'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tên prompt'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả prompt'),
    sa.Column('prompt_content', sa.Text(), nullable=False, comment='Nội dung prompt'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Phân loại'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='Mảng nhãn'),
    sa.Column('author_display_name', sa.String(length=100), nullable=True, comment='Tên tác giả muốn hiển thị'),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True, comment='Có đăng ẩn danh không'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Trạng thái: pending/approved/rejected'),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True, comment='ID người kiểm duyệt (quản trị viên đám mây)'),
    sa.Column('review_note', sa.Text(), nullable=True, comment='Ghi chú kiểm duyệt (lý do từ chối v.v.)'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='Thời gian kiểm duyệt'),
    sa.Column('workshop_item_id', sa.String(length=36), nullable=True, comment='ID hạng mục xưởng liên kết sau khi duyệt'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Thời gian cập nhật'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submissions_created_at', 'prompt_submissions', ['created_at'], unique=False)
    op.create_index('idx_submissions_source', 'prompt_submissions', ['source_instance'], unique=False)
    op.create_index('idx_submissions_status', 'prompt_submissions', ['status'], unique=False)
    op.create_index('idx_submissions_submitter', 'prompt_submissions', ['submitter_id'], unique=False)
    op.create_table('prompt_workshop_items',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tên prompt'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả prompt'),
    sa.Column('prompt_content', sa.Text(), nullable=False, comment='Nội dung prompt'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Phân loại'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='Mảng nhãn'),
    sa.Column('author_id', sa.String(length=255), nullable=True, comment='Định danh người dùng tác giả (ID instance:ID người dùng)'),
    sa.Column('author_name', sa.String(length=100), nullable=True, comment='Tên hiển thị tác giả'),
    sa.Column('source_instance', sa.String(length=255), nullable=True, comment='Định danh instance nguồn'),
    sa.Column('is_official', sa.Boolean(), nullable=True, comment='Có phải prompt chính thức không'),
    sa.Column('download_count', sa.Integer(), nullable=True, comment='Số lần tải/nhập'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='Số lượt thích'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Trạng thái: active/hidden/deprecated'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Thời gian cập nhật'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workshop_items_category', 'prompt_workshop_items', ['category'], unique=False)
    op.create_index('idx_workshop_items_created_at', 'prompt_workshop_items', ['created_at'], unique=False)
    op.create_index('idx_workshop_items_download_count', 'prompt_workshop_items', ['download_count'], unique=False)
    op.create_index('idx_workshop_items_status', 'prompt_workshop_items', ['status'], unique=False)
    op.create_table('prompt_workshop_likes',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('user_identifier', sa.String(length=255), nullable=False, comment='Định danh người dùng (ID instance:ID người dùng)'),
    sa.Column('workshop_item_id', sa.String(length=36), nullable=False, comment='ID hạng mục xưởng'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Thời gian tạo'),
    sa.ForeignKeyConstraint(['workshop_item_id'], ['prompt_workshop_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_likes_user_item', 'prompt_workshop_likes', ['user_identifier', 'workshop_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_likes_user_item', table_name='prompt_workshop_likes')
    op.drop_table('prompt_workshop_likes')
    op.drop_index('idx_workshop_items_status', table_name='prompt_workshop_items')
    op.drop_index('idx_workshop_items_download_count', table_name='prompt_workshop_items')
    op.drop_index('idx_workshop_items_created_at', table_name='prompt_workshop_items')
    op.drop_index('idx_workshop_items_category', table_name='prompt_workshop_items')
    op.drop_table('prompt_workshop_items')
    op.drop_index('idx_submissions_submitter', table_name='prompt_submissions')
    op.drop_index('idx_submissions_status', table_name='prompt_submissions')
    op.drop_index('idx_submissions_source', table_name='prompt_submissions')
    op.drop_index('idx_submissions_created_at', table_name='prompt_submissions')
    op.drop_table('prompt_submissions')
    # ### end Alembic commands ###