"""Thêm bảng thông báo

Revision ID: acdb1d611064
Revises: abc12345
Create Date: 2026-05-13 10:09:15.393713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acdb1d611064'
down_revision: Union[str, None] = 'abc12345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('title', sa.String(length=120), nullable=False, comment='Tiêu đề thông báo'),
    sa.Column('content', sa.Text(), nullable=False, comment='Nội dung thông báo'),
    sa.Column('summary', sa.String(length=255), nullable=True, comment='Tóm tắt thông báo'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='Cấp độ: info/success/warning/error'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Trạng thái: draft/published/hidden'),
    sa.Column('pinned', sa.Boolean(), nullable=False, comment='Có ghim lên đầu hay không'),
    sa.Column('author_id', sa.String(length=100), nullable=True, comment='ID quản trị viên đăng'),
    sa.Column('author_name', sa.String(length=100), nullable=True, comment='Tên hiển thị quản trị viên đăng'),
    sa.Column('publish_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Thời gian đăng'),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='Thời gian hết hạn'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Thời gian cập nhật'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_announcements_pinned', 'announcements', ['pinned'], unique=False)
    op.create_index('idx_announcements_publish_at', 'announcements', ['publish_at'], unique=False)
    op.create_index('idx_announcements_status', 'announcements', ['status'], unique=False)
    op.create_index('idx_announcements_updated_at', 'announcements', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_announcements_updated_at', table_name='announcements')
    op.drop_index('idx_announcements_status', table_name='announcements')
    op.drop_index('idx_announcements_publish_at', table_name='announcements')
    op.drop_index('idx_announcements_pinned', table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###