"""Khởi tạo database SQLite

Revision ID: fbeb1038c728
Revises: 
Create Date: 2025-12-26 13:22:53.151546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbeb1038c728'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_generation_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='ID dự án'),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='ID người dùng'),
    sa.Column('start_chapter_number', sa.Integer(), nullable=False, comment='Số thứ tự chương bắt đầu'),
    sa.Column('chapter_count', sa.Integer(), nullable=False, comment='Số chương cần sinh'),
    sa.Column('chapter_ids', sa.JSON(), nullable=False, comment='Danh sách ID chương cần sinh'),
    sa.Column('style_id', sa.Integer(), nullable=True, comment='ID phong cách viết đã dùngID'),
    sa.Column('target_word_count', sa.Integer(), nullable=True, comment='Số từ mục tiêu'),
    sa.Column('enable_analysis', sa.Boolean(), nullable=True, comment='Có bật phân tích đồng bộ không'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Trạng thái task: pending/running/completed/failed/cancelled'),
    sa.Column('total_chapters', sa.Integer(), nullable=True, comment='Tổng số chương'),
    sa.Column('completed_chapters', sa.Integer(), nullable=True, comment='Số chương đã hoàn thành'),
    sa.Column('failed_chapters', sa.JSON(), nullable=True, comment='Danh sách thông tin chương thất bại'),
    sa.Column('current_chapter_id', sa.String(length=36), nullable=True, comment='ID chương đang sinh hiện tạiID'),
    sa.Column('current_chapter_number', sa.Integer(), nullable=True, comment='Số thứ tự chương đang sinh hiện tại'),
    sa.Column('current_retry_count', sa.Integer(), nullable=True, comment='Số lần thử lại của chương hiện tại'),
    sa.Column('max_retries', sa.Integer(), nullable=True, comment='Số lần thử lại tối đa'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Thời gian bắt đầu'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Thời gian hoàn thành'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='Thông tin lỗi'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_plugins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='ID người dùng'),
    sa.Column('plugin_name', sa.String(length=100), nullable=False, comment='Tên plugin (định danh duy nhất)'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='Tên hiển thị'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả plugin'),
    sa.Column('plugin_type', sa.String(length=50), nullable=True, comment='Loại plugin: http/stdio'),
    sa.Column('server_url', sa.String(length=500), nullable=True, comment='URL máy chủ (kiểu HTTP)'),
    sa.Column('command', sa.String(length=500), nullable=True, comment='Lệnh khởi động (kiểu stdio)'),
    sa.Column('args', sa.JSON(), nullable=True, comment='Tham số lệnh (kiểu stdio)'),
    sa.Column('env', sa.JSON(), nullable=True, comment='Biến môi trường'),
    sa.Column('headers', sa.JSON(), nullable=True, comment='Header HTTP'),
    sa.Column('config', sa.JSON(), nullable=True, comment='Cấu hình riêng của plugin (JSON)（JSON）'),
    sa.Column('tools', sa.JSON(), nullable=True, comment='Danh sách công cụ cung cấp'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='Có bật không'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Trạng thái: active/inactive/error'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Thông tin lỗi cuối cùng'),
    sa.Column('last_test_at', sa.DateTime(), nullable=True, comment='Thời gian kiểm tra cuối cùng'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Phân loại'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='Thứ tự sắp xếp'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_plugins', schema=None) as batch_op:
        batch_op.create_index('idx_user_enabled', ['user_id', 'enabled'], unique=False)
        batch_op.create_index('idx_user_plugin', ['user_id', 'plugin_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_mcp_plugins_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='ID người dùng'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Tiêu đề dự án'),
    sa.Column('description', sa.Text(), nullable=True, comment='Giới thiệu dự án'),
    sa.Column('theme', sa.Text(), nullable=True, comment='Chủ đề'),
    sa.Column('genre', sa.String(length=50), nullable=True, comment='Thể loại tiểu thuyết'),
    sa.Column('target_words', sa.Integer(), nullable=True, comment='Số từ mục tiêu'),
    sa.Column('current_words', sa.Integer(), nullable=True, comment='Số từ hiện tại'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Trạng thái sáng tác'),
    sa.Column('wizard_status', sa.String(length=20), nullable=True, comment='Trạng thái hoàn thành hướng dẫn: incomplete/completed'),
    sa.Column('wizard_step', sa.Integer(), nullable=True, comment='Bước hiện tại của hướng dẫn: 0-4'),
    sa.Column('outline_mode', sa.String(length=20), nullable=False, comment='Chế độ chương dàn ý: one-to-one (chế độ truyền thống) hoặc one-to-many (chế độ chi tiết hóa)'),
    sa.Column('world_time_period', sa.Text(), nullable=True, comment='Bối cảnh thời gian'),
    sa.Column('world_location', sa.Text(), nullable=True, comment='Vị trí địa lý'),
    sa.Column('world_atmosphere', sa.Text(), nullable=True, comment='Không khí chủ đạo'),
    sa.Column('world_rules', sa.Text(), nullable=True, comment='Quy tắc thế giới'),
    sa.Column('chapter_count', sa.Integer(), nullable=True, comment='Số chương'),
    sa.Column('narrative_perspective', sa.String(length=50), nullable=True, comment='Góc nhìn trần thuật：first_person/third_person/omniscient'),
    sa.Column('character_count', sa.Integer(), nullable=True, comment='Số nhân vật'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.CheckConstraint("outline_mode IN ('one-to-one', 'one-to-many')", name='check_outline_mode'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='ID người dùng'),
    sa.Column('template_key', sa.String(length=100), nullable=False, comment='Tên key template'),
    sa.Column('template_name', sa.String(length=200), nullable=False, comment='Tên hiển thị template'),
    sa.Column('template_content', sa.Text(), nullable=False, comment='Nội dung template'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả template'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Phân loại template'),
    sa.Column('parameters', sa.Text(), nullable=True, comment='Định nghĩa tham số template (JSON)(JSON)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Có bật không'),
    sa.Column('is_system_default', sa.Boolean(), nullable=True, comment='Có phải template mặc định hệ thống không'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index('idx_user_template', ['user_id', 'template_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_prompt_templates_user_id'), ['user_id'], unique=False)

    op.create_table('relationship_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Tên quan hệ'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='Phân loại: family/social/hostile/professional'),
    sa.Column('reverse_name', sa.String(length=50), nullable=True, comment='Tên quan hệ ngược'),
    sa.Column('intimacy_range', sa.String(length=20), nullable=True, comment='Phạm vi thân mật：high/medium/low'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='Biểu tượng icon'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả quan hệ'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationship_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationship_types_id'), ['id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='ID người dùng'),
    sa.Column('api_provider', sa.String(length=50), nullable=True, comment='Nhà cung cấp API'),
    sa.Column('api_key', sa.String(length=500), nullable=True, comment='API key'),
    sa.Column('api_base_url', sa.String(length=500), nullable=True, comment='Địa chỉ API tùy chỉnh'),
    sa.Column('llm_model', sa.String(length=100), nullable=True, comment='Tên model'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='Tham số temperature'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='Số token tối đa'),
    sa.Column('preferences', sa.Text(), nullable=True, comment='Cài đặt tùy chọn khác (JSON)(JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_user_id'), ['user_id'], unique=True)

    op.create_table('user_passwords',
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='ID người dùng'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Tên đăng nhập'),
    sa.Column('password_hash', sa.String(length=64), nullable=False, comment='Hash mật khẩu (SHA256)（SHA256）'),
    sa.Column('has_custom_password', sa.Boolean(), nullable=True, comment='Có phải mật khẩu tùy chỉnh không'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user_passwords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_passwords_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='ID người dùng, định dạng: linuxdo_{id} hoặc local_{id}'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Tên đăng nhập'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='Tên hiển thị'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='URL avatar'),
    sa.Column('trust_level', sa.Integer(), nullable=True, comment='Cấp tin cậy（chỉ dùng để hiển thị）'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='Có phải quản trị viên không'),
    sa.Column('linuxdo_id', sa.String(length=100), nullable=False, comment='ID người dùng LinuxDO hoặc user local'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian đăng nhập cuối cùng'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_linuxdo_id'), ['linuxdo_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('careers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tên nghề nghiệp'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Loại nghề nghiệp: main (nghề chính)/sub (nghề phụ)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả nghề nghiệp'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Phân loại nghề nghiệp (ví dụ: hệ chiến đấu, hệ sản xuất, hệ hỗ trợ)'),
    sa.Column('stages', sa.Text(), nullable=False, comment="Danh sách giai đoạn nghề nghiệp (JSON): [{level:1, name:'', description:''}, ...]"),
    sa.Column('max_stage', sa.Integer(), nullable=False, comment='Số giai đoạn tối đa'),
    sa.Column('requirements', sa.Text(), nullable=True, comment='Yêu cầu/hạn chế nghề nghiệp'),
    sa.Column('special_abilities', sa.Text(), nullable=True, comment='Mô tả năng lực đặc biệt'),
    sa.Column('worldview_rules', sa.Text(), nullable=True, comment='Liên kết quy tắc thế giới quan'),
    sa.Column('attribute_bonuses', sa.Text(), nullable=True, comment="Cộng thuộc tính (JSON): {strength: '+10%', intelligence: '+5%'}"),
    sa.Column('source', sa.String(length=20), nullable=True, comment='Nguồn: ai/manual'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.create_index('idx_project_id', ['project_id'], unique=False)
        batch_op.create_index('idx_type', ['type'], unique=False)

    op.create_table('outlines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Tiêu đề dàn ý'),
    sa.Column('content', sa.Text(), nullable=True, comment='Nội dung dàn ý'),
    sa.Column('structure', sa.Text(), nullable=True, comment='Dữ liệu dàn ý có cấu trúc (JSON)(JSON)'),
    sa.Column('order_index', sa.Integer(), nullable=True, comment='Số thứ tự sắp xếp'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing_styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='ID người dùng sở hữuID（NULLNULL nghĩa là phong cách preset toàn cục）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tên phong cách'),
    sa.Column('style_type', sa.String(length=50), nullable=False, comment='Loại phong cách：preset/custom'),
    sa.Column('preset_id', sa.String(length=50), nullable=True, comment='ID phong cách preset: natural/classical/modern...'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả phong cách'),
    sa.Column('prompt_content', sa.Text(), nullable=False, comment='Nội dung prompt phong cách'),
    sa.Column('order_index', sa.Integer(), nullable=True, comment='Số thứ tự sắp xếp'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False, comment='Số thứ tự chương'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Tiêu đề chương'),
    sa.Column('content', sa.Text(), nullable=True, comment='Nội dung chương'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Tóm tắt chương'),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='Thống kê số từ'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Trạng thái chương'),
    sa.Column('outline_id', sa.String(length=36), nullable=True, comment='ID dàn ý liên quanID'),
    sa.Column('sub_index', sa.Integer(), nullable=True, comment='Số thứ tự chương con thuộc dàn ý'),
    sa.Column('expansion_plan', sa.Text(), nullable=True, comment='Chi tiết kế hoạch triển khai (JSON): gồm key_events, character_focus, emotional_tone...'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['outline_id'], ['outlines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tên nhân vật/tổ chức'),
    sa.Column('age', sa.String(length=50), nullable=True, comment='Tuổi'),
    sa.Column('gender', sa.String(length=50), nullable=True, comment='Giới tính'),
    sa.Column('is_organization', sa.Boolean(), nullable=True, comment='Có phải tổ chức không'),
    sa.Column('role_type', sa.String(length=50), nullable=True, comment='Loại nhân vật'),
    sa.Column('personality', sa.Text(), nullable=True, comment='đặc điểm tính cách/đặc tính tổ chức'),
    sa.Column('background', sa.Text(), nullable=True, comment='Câu chuyện nền'),
    sa.Column('appearance', sa.Text(), nullable=True, comment='Mô tả ngoại hình'),
    sa.Column('relationships', sa.Text(), nullable=True, comment='Quan hệ nhân vật (JSON)(JSON)'),
    sa.Column('organization_type', sa.String(length=100), nullable=True, comment='Loại tổ chức'),
    sa.Column('organization_purpose', sa.String(length=500), nullable=True, comment='Mục đích tổ chức'),
    sa.Column('organization_members', sa.Text(), nullable=True, comment='Thành viên tổ chức (JSON)(JSON)'),
    sa.Column('main_career_id', sa.String(length=36), nullable=True, comment='ID nghề chính'),
    sa.Column('main_career_stage', sa.Integer(), nullable=True, comment='Giai đoạn hiện tại của nghề chính'),
    sa.Column('sub_careers', sa.Text(), nullable=True, comment='Danh sách nghề phụ (JSON)(JSON): [{"career_id": "xxx", "stage": 3}, ...]'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='URL avatar'),
    sa.Column('traits', sa.Text(), nullable=True, comment='Tag đặc trưng (JSON)(JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['main_career_id'], ['careers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_default_styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='ID dự án'),
    sa.Column('style_id', sa.Integer(), nullable=False, comment='ID phong cách'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['writing_styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uix_project_default_style')
    )
    op.create_table('analysis_tasks',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID task'),
    sa.Column('chapter_id', sa.String(length=36), nullable=False, comment='ID chương'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='ID người dùng'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='ID dự án'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Trạng thái task: pending/running/completed/failed'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='Tiến độ 0-100'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Thông tin lỗi'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Thời gian bắt đầu thực thi'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Thời gian hoàn thành'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_chapter_id_created', ['chapter_id', 'created_at'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)

    op.create_table('character_careers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('career_id', sa.String(length=36), nullable=False),
    sa.Column('career_type', sa.String(length=20), nullable=False, comment='main (nghề chính)/sub (nghề phụ)'),
    sa.Column('current_stage', sa.Integer(), nullable=False, comment='Giai đoạn hiện tại（Giá trị tương ứng trong nghề nghiệp）'),
    sa.Column('stage_progress', sa.Integer(), nullable=True, comment='Tiến độ trong giai đoạn（0-100）'),
    sa.Column('started_at', sa.String(length=100), nullable=True, comment='Thời gian bắt đầu tu luyện（dòng thời gian tiểu thuyết）'),
    sa.Column('reached_current_stage_at', sa.String(length=100), nullable=True, comment='Thời gian đạt giai đoạn hiện tại'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Ghi chú (ví dụ: tâm đắc tu luyện, sự kiện đặc biệt)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_careers', schema=None) as batch_op:
        batch_op.create_index('idx_career_type', ['career_type'], unique=False)
        batch_op.create_index('idx_character_career', ['character_id', 'career_id'], unique=True)
        batch_op.create_index('idx_character_id', ['character_id'], unique=False)

    op.create_table('character_relationships',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID quan hệ'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='ID dự án'),
    sa.Column('character_from_id', sa.String(length=36), nullable=False, comment='ID nhân vật A'),
    sa.Column('character_to_id', sa.String(length=36), nullable=False, comment='ID nhân vật B'),
    sa.Column('relationship_type_id', sa.Integer(), nullable=True, comment='Loại quan hệID'),
    sa.Column('relationship_name', sa.String(length=100), nullable=True, comment='Tên quan hệ tùy chỉnh'),
    sa.Column('intimacy_level', sa.Integer(), nullable=True, comment='Mức thân mật: -100 đến 100'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Trạng thái: active/broken/past/complicated'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả chi tiết quan hệ'),
    sa.Column('started_at', sa.String(length=100), nullable=True, comment='Thời gian bắt đầu quan hệ (thời gian truyện)（thời gian truyện）'),
    sa.Column('ended_at', sa.String(length=100), nullable=True, comment='Thời gian kết thúc quan hệ (thời gian truyện)（thời gian truyện）'),
    sa.Column('source', sa.String(length=20), nullable=True, comment='Nguồn: ai/manual/imported'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['character_from_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_to_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_type_id'], ['relationship_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_relationships_character_from_id'), ['character_from_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_relationships_character_to_id'), ['character_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_relationships_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_relationships_relationship_type_id'), ['relationship_type_id'], unique=False)

    op.create_table('generation_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True, comment='Prompt đã dùng'),
    sa.Column('generated_content', sa.Text(), nullable=True, comment='Nội dung đã sinh'),
    sa.Column('model', sa.String(length=50), nullable=True, comment='Model đã dùng'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Số token đã tiêu thụ'),
    sa.Column('generation_time', sa.Float(), nullable=True, comment='Thời gian sinh (giây)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID tổ chức'),
    sa.Column('character_id', sa.String(length=36), nullable=False, comment='ID nhân vật liên quanID'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='ID dự án'),
    sa.Column('parent_org_id', sa.String(length=36), nullable=True, comment='ID tổ chức cha'),
    sa.Column('level', sa.Integer(), nullable=True, comment='Cấp tổ chức'),
    sa.Column('power_level', sa.Integer(), nullable=True, comment='Cấp thế lực：0-100'),
    sa.Column('member_count', sa.Integer(), nullable=True, comment='Số thành viên'),
    sa.Column('location', sa.Text(), nullable=True, comment='Nơi ở'),
    sa.Column('motto', sa.String(length=200), nullable=True, comment='Tôn chỉ/khẩu hiệu'),
    sa.Column('color', sa.String(length=100), nullable=True, comment='Màu đại diện'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_project_id'), ['project_id'], unique=False)

    op.create_table('plot_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('plot_stage', sa.String(length=50), nullable=True, comment='Giai đoạn cốt truyện: 开端/发展/高潮/结局/过渡'),
    sa.Column('conflict_level', sa.Integer(), nullable=True, comment='Cường độ xung đột 1-10'),
    sa.Column('conflict_types', sa.JSON(), nullable=True, comment="Danh sách loại xung đột: ['人与人', '人与己', '人与环境']"),
    sa.Column('emotional_tone', sa.String(length=100), nullable=True, comment='Cảm xúc chủ đạo: 紧张/温馨/悲伤/激昂/平静'),
    sa.Column('emotional_intensity', sa.Float(), nullable=True, comment='Cường độ cảm xúc 0.0-1.0'),
    sa.Column('emotional_curve', sa.JSON(), nullable=True, comment='Đường cong cảm xúc: {start: 0.3, middle: 0.7, end: 0.5}'),
    sa.Column('hooks', sa.JSON(), nullable=True, comment='Danh sách hook - yếu tố thu hút độc giả: [\n        {\n            "type": "悬念|情感|冲突|认知",\n            "content": "Nội dung cụ thể",\n            "strength": 8,\n            "position": "开头|中段|结尾"\n        }\n    ]'),
    sa.Column('hooks_count', sa.Integer(), nullable=True, comment='Số hook'),
    sa.Column('hooks_avg_strength', sa.Float(), nullable=True, comment='Cường độ hook trung bình'),
    sa.Column('foreshadows', sa.JSON(), nullable=True, comment='Danh sách phục bút: [\n        {\n            "content": "Nội dung phục bút",\n            "type": "planted|resolved",\n            "strength": 7,\n            "subtlety": 8,\n            "reference_chapter": 3\n        }\n    ]'),
    sa.Column('foreshadows_planted', sa.Integer(), nullable=True, comment='Số phục bút đã gieo trong chương này'),
    sa.Column('foreshadows_resolved', sa.Integer(), nullable=True, comment='Số phục bút thu hồi trong chương này'),
    sa.Column('plot_points', sa.JSON(), nullable=True, comment='Danh sách nút cốt truyện: [\n        {\n            "content": "Mô tả nút cốt truyện",\n            "importance": 0.9,\n            "type": "revelation|conflict|resolution|transition",\n            "impact": "Mô tả ảnh hưởng tới câu chuyện"\n        }\n    ]'),
    sa.Column('plot_points_count', sa.Integer(), nullable=True, comment='Số nút cốt truyện'),
    sa.Column('character_states', sa.JSON(), nullable=True, comment='Thay đổi trạng thái nhân vật: [\n        {\n            "character_id": "xxx",\n            "character_name": "Trương Tam",\n            "state_before": "do dự thiếu quyết đoán",\n            "state_after": "niềm tin kiên định",\n            "psychological_change": "mô tả nội tâm",\n            "key_event": "Sự kiện kích hoạt",\n            "relationship_changes": {"Lý Tứ": "thay đổi quan hệ"}\n        }\n    ]'),
    sa.Column('scenes', sa.JSON(), nullable=True, comment="Danh sách cảnh: [{location: '地点', atmosphere: '氛围', duration: '时长'}]"),
    sa.Column('pacing', sa.String(length=50), nullable=True, comment='Nhịp độ: slow|moderate|fast|varied'),
    sa.Column('overall_quality_score', sa.Float(), nullable=True, comment='Điểm chất lượng tổng thể 0.0-10.0'),
    sa.Column('pacing_score', sa.Float(), nullable=True, comment='Điểm nhịp độ 0.0-10.0'),
    sa.Column('engagement_score', sa.Float(), nullable=True, comment='Điểm hấp dẫn 0.0-10.0'),
    sa.Column('coherence_score', sa.Float(), nullable=True, comment='Điểm mạch lạc 0.0-10.0'),
    sa.Column('analysis_report', sa.Text(), nullable=True, comment='Báo cáo phân tích văn bản đầy đủ'),
    sa.Column('suggestions', sa.JSON(), nullable=True, comment="Danh sách gợi ý cải thiện: ['建议1', '建议2']"),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='Số từ chương'),
    sa.Column('dialogue_ratio', sa.Float(), nullable=True, comment='Tỷ lệ đối thoại 0.0-1.0'),
    sa.Column('description_ratio', sa.Float(), nullable=True, comment='Tỷ lệ miêu tả 0.0-1.0'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian phân tích'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plot_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_analysis_chapter_id'), ['chapter_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_plot_analysis_project_id'), ['project_id'], unique=False)

    op.create_table('regeneration_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True, comment='ID kết quả phân tích liên quanID'),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('modification_instructions', sa.Text(), nullable=False, comment='Chỉ thị chỉnh sửa tổng hợp'),
    sa.Column('original_suggestions', sa.JSON(), nullable=True, comment='Danh sách gợi ý gốc từ phân tích'),
    sa.Column('selected_suggestion_indices', sa.JSON(), nullable=True, comment='Chỉ mục gợi ý người dùng đã chọn'),
    sa.Column('custom_instructions', sa.Text(), nullable=True, comment='Ý kiến chỉnh sửa tùy chỉnh của người dùng'),
    sa.Column('style_id', sa.Integer(), nullable=True, comment='Phong cách viếtID'),
    sa.Column('target_word_count', sa.Integer(), nullable=True, comment='Số từ mục tiêu'),
    sa.Column('focus_areas', sa.JSON(), nullable=True, comment='Hướng tối ưu trọng điểm'),
    sa.Column('preserve_elements', sa.JSON(), nullable=True, comment='Cấu hình yếu tố cần giữ lại'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending/running/completed/failed'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='Tiến độ 0-100'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True, comment='Snapshot nội dung chương gốc'),
    sa.Column('original_word_count', sa.Integer(), nullable=True, comment='Số từ gốc'),
    sa.Column('regenerated_content', sa.Text(), nullable=True, comment='Nội dung tái sinh'),
    sa.Column('regenerated_word_count', sa.Integer(), nullable=True, comment='Số từ nội dung mới'),
    sa.Column('version_number', sa.Integer(), nullable=True, comment='Số phiên bản'),
    sa.Column('version_note', sa.String(length=500), nullable=True, comment='Ghi chú phiên bản'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regeneration_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regeneration_tasks_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regeneration_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regeneration_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('story_memories',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=False, comment='\n    Loại ký ức:\n    - plot_point: nút cốt truyện\n    - character_event: sự kiện nhân vật\n    - world_detail: chi tiết thế giới quan\n    - hook: hook (hồi hộp/xung đột)\n    - foreshadow: phục bút\n    - dialogue: đối thoại quan trọng\n    - scene: miêu tả cảnh\n    '),
    sa.Column('title', sa.String(length=200), nullable=True, comment='Tiêu đề/tóm tắt ký ức'),
    sa.Column('content', sa.Text(), nullable=False, comment='Tóm tắt nội dung ký ức (100-500 từ)'),
    sa.Column('full_context', sa.Text(), nullable=True, comment='Ngữ cảnh đầy đủ (tùy chọn, dùng để ghi chi tiết)'),
    sa.Column('related_characters', sa.JSON(), nullable=True, comment="Danh sách ID nhân vật liên quan: ['char_id_1', 'char_id_2']"),
    sa.Column('related_locations', sa.JSON(), nullable=True, comment="Danh sách địa điểm liên quan: ['地点1', '地点2']"),
    sa.Column('tags', sa.JSON(), nullable=True, comment="Danh sách tag: ['悬念', '转折', '伏笔', '高潮']"),
    sa.Column('importance_score', sa.Float(), nullable=True, comment='Điểm quan trọng 0.0-1.0'),
    sa.Column('story_timeline', sa.Integer(), nullable=False, comment='Vị trí dòng thời gian câu chuyện (số thứ tự chương)(Số thứ tự chương)'),
    sa.Column('chapter_position', sa.Integer(), nullable=True, comment='Vị trí trong chương(vị trí ký tự)'),
    sa.Column('text_length', sa.Integer(), nullable=True, comment='Độ dài văn bản (số ký tự)'),
    sa.Column('is_foreshadow', sa.Integer(), nullable=True, comment='Trạng thái phục bút: 0=ký ức thường, 1=đã gieo phục bút, 2=phục bút đã thu hồi'),
    sa.Column('foreshadow_resolved_at', sa.String(length=100), nullable=True, comment='ID chương thu hồi phục bútID'),
    sa.Column('foreshadow_strength', sa.Float(), nullable=True, comment='Cường độ phục bút 0.0-1.0'),
    sa.Column('vector_id', sa.String(length=100), nullable=True, comment='ID duy nhất trong database vectorID'),
    sa.Column('embedding_model', sa.String(length=100), nullable=True, comment='Model embedding đã dùng'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['foreshadow_resolved_at'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vector_id')
    )
    with op.batch_alter_table('story_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_memories_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_memories_memory_type'), ['memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_memories_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_memories_story_timeline'), ['story_timeline'], unique=False)

    op.create_table('organization_members',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID quan hệ thành viên'),
    sa.Column('organization_id', sa.String(length=36), nullable=False, comment='ID tổ chức'),
    sa.Column('character_id', sa.String(length=36), nullable=False, comment='ID nhân vật'),
    sa.Column('position', sa.String(length=100), nullable=False, comment='Tên chức vụ'),
    sa.Column('rank', sa.Integer(), nullable=True, comment='Cấp bậc chức vụ'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Trạng thái: active/retired/expelled/deceased'),
    sa.Column('joined_at', sa.String(length=100), nullable=True, comment='Thời gian gia nhập (thời gian truyện)（thời gian truyện）'),
    sa.Column('left_at', sa.String(length=100), nullable=True, comment='Thời gian rời đi (thời gian truyện)（thời gian truyện）'),
    sa.Column('loyalty', sa.Integer(), nullable=True, comment='Mức trung thành: 0-100'),
    sa.Column('contribution', sa.Integer(), nullable=True, comment='Mức đóng góp: 0-100'),
    sa.Column('source', sa.String(length=20), nullable=True, comment='Nguồn: ai/manual'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Ghi chú'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_character_id'))

    op.drop_table('organization_members')
    with op.batch_alter_table('story_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_memories_story_timeline'))
        batch_op.drop_index(batch_op.f('ix_story_memories_project_id'))
        batch_op.drop_index(batch_op.f('ix_story_memories_memory_type'))
        batch_op.drop_index(batch_op.f('ix_story_memories_chapter_id'))

    op.drop_table('story_memories')
    with op.batch_alter_table('regeneration_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regeneration_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_regeneration_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_regeneration_tasks_chapter_id'))

    op.drop_table('regeneration_tasks')
    with op.batch_alter_table('plot_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_analysis_project_id'))
        batch_op.drop_index(batch_op.f('ix_plot_analysis_chapter_id'))

    op.drop_table('plot_analysis')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_project_id'))

    op.drop_table('organizations')
    op.drop_table('generation_history')
    with op.batch_alter_table('character_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_relationships_relationship_type_id'))
        batch_op.drop_index(batch_op.f('ix_character_relationships_project_id'))
        batch_op.drop_index(batch_op.f('ix_character_relationships_character_to_id'))
        batch_op.drop_index(batch_op.f('ix_character_relationships_character_from_id'))

    op.drop_table('character_relationships')
    with op.batch_alter_table('character_careers', schema=None) as batch_op:
        batch_op.drop_index('idx_character_id')
        batch_op.drop_index('idx_character_career')
        batch_op.drop_index('idx_career_type')

    op.drop_table('character_careers')
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_chapter_id_created')

    op.drop_table('analysis_tasks')
    op.drop_table('project_default_styles')
    op.drop_table('characters')
    op.drop_table('chapters')
    op.drop_table('writing_styles')
    op.drop_table('outlines')
    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.drop_index('idx_type')
        batch_op.drop_index('idx_project_id')

    op.drop_table('careers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_linuxdo_id'))

    op.drop_table('users')
    with op.batch_alter_table('user_passwords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_passwords_user_id'))

    op.drop_table('user_passwords')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_user_id'))
        batch_op.drop_index('idx_user_id')

    op.drop_table('settings')
    with op.batch_alter_table('relationship_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_types_id'))

    op.drop_table('relationship_types')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_user_id'))
        batch_op.drop_index('idx_user_template')

    op.drop_table('prompt_templates')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))

    op.drop_table('projects')
    with op.batch_alter_table('mcp_plugins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_plugins_user_id'))
        batch_op.drop_index('idx_user_plugin')
        batch_op.drop_index('idx_user_enabled')

    op.drop_table('mcp_plugins')
    op.drop_table('batch_generation_tasks')
    # ### end Alembic commands ###