"""Thêm cấu trúc bảng liên quan xưởng prompt

Revision ID: 927bcb55b756
Revises: 951919659e0f
Create Date: 2026-01-27 13:54:34.486645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927bcb55b756'
down_revision: Union[str, None] = '951919659e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_submissions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('submitter_id', sa.String(length=255), nullable=False, comment='Định danh người gửi (instance ID:user ID)'),
    sa.Column('submitter_name', sa.String(length=100), nullable=True, comment='Tên hiển thị người gửi'),
    sa.Column('source_instance', sa.String(length=255), nullable=False, comment='Định danh instance nguồn'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tên prompt'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả prompt'),
    sa.Column('prompt_content', sa.Text(), nullable=False, comment='Nội dung prompt'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Phân loại'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='Mảng tag'),
    sa.Column('author_display_name', sa.String(length=100), nullable=True, comment='Tên tác giả muốn hiển thị'),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True, comment='Có đăng ẩn danh không'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Trạng thái: pending/approved/rejected'),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True, comment='ID người duyệt (quản trị viên cloud)'),
    sa.Column('review_note', sa.Text(), nullable=True, comment='Ghi chú duyệt（lý do từ chối...）'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='Thời gian duyệt'),
    sa.Column('workshop_item_id', sa.String(length=36), nullable=True, comment='ID mục workshop liên kết sau khi duyệtID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_submissions', schema=None) as batch_op:
        batch_op.create_index('idx_submissions_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_submissions_source', ['source_instance'], unique=False)
        batch_op.create_index('idx_submissions_status', ['status'], unique=False)
        batch_op.create_index('idx_submissions_submitter', ['submitter_id'], unique=False)

    op.create_table('prompt_workshop_items',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tên prompt'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả prompt'),
    sa.Column('prompt_content', sa.Text(), nullable=False, comment='Nội dung prompt'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Phân loại'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='Mảng tag'),
    sa.Column('author_id', sa.String(length=255), nullable=True, comment='Định danh người dùng tác giả (instance ID:user ID)'),
    sa.Column('author_name', sa.String(length=100), nullable=True, comment='Tên hiển thị tác giả'),
    sa.Column('source_instance', sa.String(length=255), nullable=True, comment='Định danh instance nguồn'),
    sa.Column('is_official', sa.Boolean(), nullable=True, comment='Có phải prompt chính thức không'),
    sa.Column('download_count', sa.Integer(), nullable=True, comment='Số lần tải xuống/nhập'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='Số lượt thích'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Trạng thái: active/hidden/deprecated'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_workshop_items', schema=None) as batch_op:
        batch_op.create_index('idx_workshop_items_category', ['category'], unique=False)
        batch_op.create_index('idx_workshop_items_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_workshop_items_download_count', ['download_count'], unique=False)
        batch_op.create_index('idx_workshop_items_status', ['status'], unique=False)

    op.create_table('prompt_workshop_likes',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('user_identifier', sa.String(length=255), nullable=False, comment='Định danh người dùng (instance ID:user ID)'),
    sa.Column('workshop_item_id', sa.String(length=36), nullable=False, comment='mục workshopID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.ForeignKeyConstraint(['workshop_item_id'], ['prompt_workshop_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_workshop_likes', schema=None) as batch_op:
        batch_op.create_index('idx_likes_user_item', ['user_identifier', 'workshop_item_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_workshop_likes', schema=None) as batch_op:
        batch_op.drop_index('idx_likes_user_item')

    op.drop_table('prompt_workshop_likes')
    with op.batch_alter_table('prompt_workshop_items', schema=None) as batch_op:
        batch_op.drop_index('idx_workshop_items_status')
        batch_op.drop_index('idx_workshop_items_download_count')
        batch_op.drop_index('idx_workshop_items_created_at')
        batch_op.drop_index('idx_workshop_items_category')

    op.drop_table('prompt_workshop_items')
    with op.batch_alter_table('prompt_submissions', schema=None) as batch_op:
        batch_op.drop_index('idx_submissions_submitter')
        batch_op.drop_index('idx_submissions_status')
        batch_op.drop_index('idx_submissions_source')
        batch_op.drop_index('idx_submissions_created_at')

    op.drop_table('prompt_submissions')
    # ### end Alembic commands ###