"""Thêm bảng quản lý phục bút

Revision ID: 951919659e0f
Revises: 7899f8d4d839
Create Date: 2026-01-19 10:05:40.794044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951919659e0f'
down_revision: Union[str, None] = '7899f8d4d839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreshadows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Tiêu đề phục bút'),
    sa.Column('content', sa.Text(), nullable=False, comment='Nội dung/mô tả chi tiết phục bút'),
    sa.Column('hint_text', sa.Text(), nullable=True, comment='Văn bản gợi ý khi chôn phục bút (trích văn gốc hoặc khái quát)'),
    sa.Column('resolution_text', sa.Text(), nullable=True, comment='Văn bản tiết lộ khi thu hồi phục bút (trích văn gốc hoặc khái quát)'),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='Loại nguồn: analysis=trích từ phân tích, manual=thêm thủ công'),
    sa.Column('source_memory_id', sa.String(length=100), nullable=True, comment='ID ký ức nguồn (nếu đồng bộ từ kết quả phân tích)'),
    sa.Column('source_analysis_id', sa.String(length=36), nullable=True, comment='ID task phân tích nguồn'),
    sa.Column('plant_chapter_id', sa.String(length=36), nullable=True, comment='ID chương chôn'),
    sa.Column('plant_chapter_number', sa.Integer(), nullable=True, comment='Số chương chôn (lưu dư thừa để tiện truy vấn)'),
    sa.Column('target_resolve_chapter_id', sa.String(length=36), nullable=True, comment='ID chương dự kiến thu hồi'),
    sa.Column('target_resolve_chapter_number', sa.Integer(), nullable=True, comment='Số chương dự kiến thu hồi'),
    sa.Column('actual_resolve_chapter_id', sa.String(length=36), nullable=True, comment='ID chương thu hồi thực tế'),
    sa.Column('actual_resolve_chapter_number', sa.Integer(), nullable=True, comment='Số chương thu hồi thực tế'),
            sa.Column('status', sa.String(length=20), nullable=True, comment='\n    Trạng thái phục bút:\n    - pending: chờ chôn (đã lên kế hoạch nhưng chưa ghi vào chương)\n    - planted: đã chôn (đã chôn trong chương)\n    - resolved: đã thu hồi (đã thu hồi trong chương)\n    - partially_resolved: thu hồi một phần (phục bút dài hơi có thể thu hồi nhiều lần)\n    - abandoned: đã bỏ (quyết định không dùng phục bút này nữa)\n    '),
    sa.Column('is_long_term', sa.Boolean(), nullable=True, comment='Có phải phục bút dài hơi không (phục bút quan trọng trải nhiều chương)'),
    sa.Column('importance', sa.Float(), nullable=True, comment='Điểm tầm quan trọng 0.0-1.0'),
    sa.Column('strength', sa.Integer(), nullable=True, comment='Cường độ phục bút 1-10 (ảnh hưởng độc giả mạnh cỡ nào)'),
    sa.Column('subtlety', sa.Integer(), nullable=True, comment='Độ ẩn mình 1-10 (càng cao càng kín)'),
    sa.Column('urgency', sa.Integer(), nullable=True, comment='Độ khẩn cấp: 0=không khẩn, 1=cần chú ý, 2=cần thu hồi gấp'),
    sa.Column('related_characters', sa.JSON(), nullable=True, comment="Danh sách tên nhân vật liên quan: ['Nhân vật 1', 'Nhân vật 2']"),
    sa.Column('related_foreshadow_ids', sa.JSON(), nullable=True, comment='Danh sách ID phục bút khác liên quan (chuỗi phục bút)'),
    sa.Column('tags', sa.JSON(), nullable=True, comment="Danh sách nhãn: ['thân thế', 'hồi hộp', 'bước ngoặt']"),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Phân loại: identity (thân thế), mystery (hồi hộp), item (vật phẩm), relationship (quan hệ), event (sự kiện)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Ghi chú sáng tác (chỉ tác giả thấy)'),
    sa.Column('resolution_notes', sa.Text(), nullable=True, comment='Giải thích cách thu hồi'),
    sa.Column('auto_remind', sa.Boolean(), nullable=True, comment='Có tự nhắc khi sinh chương không'),
    sa.Column('remind_before_chapters', sa.Integer(), nullable=True, comment='Bắt đầu nhắc thu hồi trước mấy chương'),
    sa.Column('include_in_context', sa.Boolean(), nullable=True, comment='Có gồm trong ngữ cảnh sinh không'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian tạo'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Thời gian cập nhật'),
    sa.Column('planted_at', sa.DateTime(), nullable=True, comment='Thời gian chôn'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='Thời gian thu hồi'),
    sa.ForeignKeyConstraint(['actual_resolve_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_resolve_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foreshadows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foreshadows_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_foreshadows_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foreshadows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foreshadows_status'))
        batch_op.drop_index(batch_op.f('ix_foreshadows_project_id'))

    op.drop_table('foreshadows')
    # ### end Alembic commands ###