"""Thêm cấu hình sinh bìa tiểu thuyết

Revision ID: 17ce752ed7cc
Revises: d887fd1a30a6
Create Date: 2026-03-16 10:58:55.143700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ce752ed7cc'
down_revision: Union[str, None] = 'd887fd1a30a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=1000), nullable=True, comment='Địa chỉ truy cập ảnh bìa'))
        batch_op.add_column(sa.Column('cover_prompt', sa.Text(), nullable=True, comment='Prompt dùng lần gần nhất khi sinh bìa'))
        batch_op.add_column(sa.Column('cover_status', sa.String(length=20), nullable=False, server_default='none', comment='Trạng thái bìa: none/generating/ready/failed'))
        batch_op.add_column(sa.Column('cover_error', sa.Text(), nullable=True, comment='Lý do thất bại lần sinh bìa gần nhất'))
        batch_op.add_column(sa.Column('cover_updated_at', sa.DateTime(), nullable=True, comment='Thời gian sinh bìa thành công gần nhất'))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_api_provider', sa.String(length=50), nullable=True, comment='Nhà cung cấp API ảnh bìa'))
        batch_op.add_column(sa.Column('cover_api_key', sa.String(length=500), nullable=True, comment='Khóa API ảnh bìa'))
        batch_op.add_column(sa.Column('cover_api_base_url', sa.String(length=500), nullable=True, comment='Địa chỉ API tùy chỉnh ảnh bìa'))
        batch_op.add_column(sa.Column('cover_image_model', sa.String(length=100), nullable=True, comment='Tên model ảnh bìa'))
        batch_op.add_column(sa.Column('cover_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0'), comment='Có bật sinh ảnh bìa không'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('cover_enabled')
        batch_op.drop_column('cover_image_model')
        batch_op.drop_column('cover_api_base_url')
        batch_op.drop_column('cover_api_key')
        batch_op.drop_column('cover_api_provider')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('cover_updated_at')
        batch_op.drop_column('cover_error')
        batch_op.drop_column('cover_status')
        batch_op.drop_column('cover_prompt')
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###